[build]
  command = "pnpm install --frozen-lockfile && pnpm build"
  publish = "out"

[build.environment]
  NODE_VERSION = "18.17.0"
  NPM_VERSION = "10.2.4"
  PNPM_VERSION = "8.15.1"
  CI = "true"

[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

[build.processing.images]
  compress = true

[build.processing.html]
  pretty_urls = true

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[plugins]]
  package = "netlify-plugin-cache"
  [plugins.inputs]
    paths = [
      "node_modules/.cache",
      ".next/cache",
      ".pnpm-store"
    ]

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 