[build]
  command = "pnpm build"
  publish = "out"

[build.environment]
  NODE_VERSION = "18.17.0"
  NPM_FLAGS = "--version"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 